/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: FleetMessages.h
  Source: FleetMessages.idl
  Cyclone DDS: V0.7.0

*****************************************************************/

#include "dds/ddsc/dds_public_impl.h"

#ifndef _DDSL_FLEETMESSAGES_H_
#define _DDSL_FLEETMESSAGES_H_


#ifdef __cplusplus
extern "C" {
#endif

#define LdmFleetData_LiftRequest_Constants_REQUEST_END_SESSION 0
#define LdmFleetData_LiftRequest_Constants_REQUEST_AGV_MODE 1
#define LdmFleetData_LiftRequest_Constants_REQUEST_HUMAN_MODE 2
#define LdmFleetData_LiftRequest_Constants_DOOR_CLOSED 0
#define LdmFleetData_LiftRequest_Constants_DOOR_OPEN 2
#define LdmFleetData_LiftState_Constants_DOOR_CLOSED 0
#define LdmFleetData_LiftState_Constants_DOOR_MOVING 1
#define LdmFleetData_LiftState_Constants_DOOR_OPEN 2
#define LdmFleetData_LiftState_Constants_MOTION_STOPPED 0
#define LdmFleetData_LiftState_Constants_MOTION_UP 1
#define LdmFleetData_LiftState_Constants_MOTION_DOWN 2
#define LdmFleetData_LiftState_Constants_MOTION_UNKNOWN 3
#define LdmFleetData_LiftState_Constants_MODE_UNKNOWN 0
#define LdmFleetData_LiftState_Constants_MODE_HUMAN 1
#define LdmFleetData_LiftState_Constants_MODE_AGV 2
#define LdmFleetData_LiftState_Constants_MODE_FIRE 3
#define LdmFleetData_LiftState_Constants_MODE_OFFLINE 4
#define LdmFleetData_LiftState_Constants_MODE_EMERGENCY 5


typedef struct LdmFleetData_LiftRequest
{
  char * request_id;
  char * lift_name;
  uint32_t request_type;
  char * destination_floor;
  uint32_t door_state;
} LdmFleetData_LiftRequest;

extern const dds_topic_descriptor_t LdmFleetData_LiftRequest_desc;

#define LdmFleetData_LiftRequest__alloc() \
((LdmFleetData_LiftRequest*) dds_alloc (sizeof (LdmFleetData_LiftRequest)));

#define LdmFleetData_LiftRequest_free(d,o) \
dds_sample_free ((d), &LdmFleetData_LiftRequest_desc, (o))


typedef struct LdmFleetData_LiftState
{
  char * lift_name;
  char * current_floor;
  uint32_t door_state;
  uint32_t motion_state;
  uint32_t current_mode;
  char * request_id;
} LdmFleetData_LiftState;

extern const dds_topic_descriptor_t LdmFleetData_LiftState_desc;

#define LdmFleetData_LiftState__alloc() \
((LdmFleetData_LiftState*) dds_alloc (sizeof (LdmFleetData_LiftState)));

#define LdmFleetData_LiftState_free(d,o) \
dds_sample_free ((d), &LdmFleetData_LiftState_desc, (o))

#ifdef __cplusplus
}
#endif
#endif /* _DDSL_FLEETMESSAGES_H_ */
